/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'accounting-type-target?': RouteRecordInfo<'accounting-type-target?', '/accounting/:type/:target?', { type: ParamValue<true>, target?: ParamValueZeroOrOne<true> }, { type: ParamValue<false>, target?: ParamValueZeroOrOne<false> }>,
    'accounting-ageing-ap': RouteRecordInfo<'accounting-ageing-ap', '/accounting/ageing-ap', Record<never, never>, Record<never, never>>,
    'accounting-ageing-ar': RouteRecordInfo<'accounting-ageing-ar', '/accounting/ageing-ar', Record<never, never>, Record<never, never>>,
    'accounting-co': RouteRecordInfo<'accounting-co', '/accounting/CO', Record<never, never>, Record<never, never>>,
    'accounting-ic': RouteRecordInfo<'accounting-ic', '/accounting/IC', Record<never, never>, Record<never, never>>,
    'accounting-id': RouteRecordInfo<'accounting-id', '/accounting/ID', Record<never, never>, Record<never, never>>,
    'accounting-journal': RouteRecordInfo<'accounting-journal', '/accounting/journal', Record<never, never>, Record<never, never>>,
    'accounting-pmt': RouteRecordInfo<'accounting-pmt', '/accounting/PMT', Record<never, never>, Record<never, never>>,
    'accounting-pnl-period': RouteRecordInfo<'accounting-pnl-period', '/accounting/pnl-period', Record<never, never>, Record<never, never>>,
    'accounting-po': RouteRecordInfo<'accounting-po', '/accounting/PO', Record<never, never>, Record<never, never>>,
    'accounting-rpt': RouteRecordInfo<'accounting-rpt', '/accounting/RPT', Record<never, never>, Record<never, never>>,
    'client': RouteRecordInfo<'client', '/client', Record<never, never>, Record<never, never>>,
    'client-id': RouteRecordInfo<'client-id', '/client/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'crm-activities': RouteRecordInfo<'crm-activities', '/crm/activities', Record<never, never>, Record<never, never>>,
    'crm-leads': RouteRecordInfo<'crm-leads', '/crm/leads', Record<never, never>, Record<never, never>>,
    'crm-opportunities': RouteRecordInfo<'crm-opportunities', '/crm/opportunities', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'inventory': RouteRecordInfo<'inventory', '/inventory', Record<never, never>, Record<never, never>>,
    'kitchen': RouteRecordInfo<'kitchen', '/kitchen', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'login-with-token-token-email': RouteRecordInfo<'login-with-token-token-email', '/login-with-token/:token/:email', { token: ParamValue<true>, email: ParamValue<true> }, { token: ParamValue<false>, email: ParamValue<false> }>,
    'loyalty': RouteRecordInfo<'loyalty', '/loyalty', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'order': RouteRecordInfo<'order', '/order', Record<never, never>, Record<never, never>>,
    'pos': RouteRecordInfo<'pos', '/pos', Record<never, never>, Record<never, never>>,
    'product': RouteRecordInfo<'product', '/product', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'register-token': RouteRecordInfo<'register-token', '/register/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    'report': RouteRecordInfo<'report', '/report', Record<never, never>, Record<never, never>>,
    'report-audit-log': RouteRecordInfo<'report-audit-log', '/report/audit-log', Record<never, never>, Record<never, never>>,
    'report-carrier-performance': RouteRecordInfo<'report-carrier-performance', '/report/carrier-performance', Record<never, never>, Record<never, never>>,
    'report-charge': RouteRecordInfo<'report-charge', '/report/charge', Record<never, never>, Record<never, never>>,
    'report-co2-emissions': RouteRecordInfo<'report-co2-emissions', '/report/co2-emissions', Record<never, never>, Record<never, never>>,
    'report-compliance-dashboard': RouteRecordInfo<'report-compliance-dashboard', '/report/compliance-dashboard', Record<never, never>, Record<never, never>>,
    'report-customer-profitability': RouteRecordInfo<'report-customer-profitability', '/report/customer-profitability', Record<never, never>, Record<never, never>>,
    'report-dataset': RouteRecordInfo<'report-dataset', '/report/dataset', Record<never, never>, Record<never, never>>,
    'report-dd-dashboard': RouteRecordInfo<'report-dd-dashboard', '/report/dd-dashboard', Record<never, never>, Record<never, never>>,
    'report-department-pnl': RouteRecordInfo<'report-department-pnl', '/report/department-pnl', Record<never, never>, Record<never, never>>,
    'report-edi-log': RouteRecordInfo<'report-edi-log', '/report/edi-log', Record<never, never>, Record<never, never>>,
    'report-exception': RouteRecordInfo<'report-exception', '/report/exception', Record<never, never>, Record<never, never>>,
    'report-insurance-declaration': RouteRecordInfo<'report-insurance-declaration', '/report/insurance-declaration', Record<never, never>, Record<never, never>>,
    'report-kpi': RouteRecordInfo<'report-kpi', '/report/kpi', Record<never, never>, Record<never, never>>,
    'report-rate-benchmark': RouteRecordInfo<'report-rate-benchmark', '/report/rate-benchmark', Record<never, never>, Record<never, never>>,
    'report-sales-commission': RouteRecordInfo<'report-sales-commission', '/report/sales-commission', Record<never, never>, Record<never, never>>,
    'report-sales-target': RouteRecordInfo<'report-sales-target', '/report/sales-target', Record<never, never>, Record<never, never>>,
    'report-shipment': RouteRecordInfo<'report-shipment', '/report/shipment', Record<never, never>, Record<never, never>>,
    'report-staff': RouteRecordInfo<'report-staff', '/report/staff', Record<never, never>, Record<never, never>>,
    'report-top-lanes': RouteRecordInfo<'report-top-lanes', '/report/top-lanes', Record<never, never>, Record<never, never>>,
    'report-vat-report': RouteRecordInfo<'report-vat-report', '/report/vat-report', Record<never, never>, Record<never, never>>,
    'setting-branch': RouteRecordInfo<'setting-branch', '/setting/branch', Record<never, never>, Record<never, never>>,
    'setting-chart-of-accounts': RouteRecordInfo<'setting-chart-of-accounts', '/setting/chart-of-accounts', Record<never, never>, Record<never, never>>,
    'setting-company': RouteRecordInfo<'setting-company', '/setting/company', Record<never, never>, Record<never, never>>,
    'setting-department': RouteRecordInfo<'setting-department', '/setting/department', Record<never, never>, Record<never, never>>,
    'setting-global-setting': RouteRecordInfo<'setting-global-setting', '/setting/global-setting', Record<never, never>, Record<never, never>>,
    'setting-groups': RouteRecordInfo<'setting-groups', '/setting/groups', Record<never, never>, Record<never, never>>,
    'setting-pages': RouteRecordInfo<'setting-pages', '/setting/pages', Record<never, never>, Record<never, never>>,
    'setting-users': RouteRecordInfo<'setting-users', '/setting/users', Record<never, never>, Record<never, never>>,
    'shift': RouteRecordInfo<'shift', '/shift', Record<never, never>, Record<never, never>>,
    'table': RouteRecordInfo<'table', '/table', Record<never, never>, Record<never, never>>,
    'user-settings': RouteRecordInfo<'user-settings', '/user-settings', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
