/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'accounting-type-target?': RouteRecordInfo<'accounting-type-target?', '/accounting/:type/:target?', { type: ParamValue<true>, target?: ParamValueZeroOrOne<true> }, { type: ParamValue<false>, target?: ParamValueZeroOrOne<false> }>,
    'accounting-ageing-ap': RouteRecordInfo<'accounting-ageing-ap', '/accounting/ageing-ap', Record<never, never>, Record<never, never>>,
    'accounting-ageing-ar': RouteRecordInfo<'accounting-ageing-ar', '/accounting/ageing-ar', Record<never, never>, Record<never, never>>,
    'accounting-co': RouteRecordInfo<'accounting-co', '/accounting/CO', Record<never, never>, Record<never, never>>,
    'accounting-ic': RouteRecordInfo<'accounting-ic', '/accounting/IC', Record<never, never>, Record<never, never>>,
    'accounting-id': RouteRecordInfo<'accounting-id', '/accounting/ID', Record<never, never>, Record<never, never>>,
    'accounting-journal': RouteRecordInfo<'accounting-journal', '/accounting/journal', Record<never, never>, Record<never, never>>,
    'accounting-pmt': RouteRecordInfo<'accounting-pmt', '/accounting/PMT', Record<never, never>, Record<never, never>>,
    'accounting-pnl-period': RouteRecordInfo<'accounting-pnl-period', '/accounting/pnl-period', Record<never, never>, Record<never, never>>,
    'accounting-po': RouteRecordInfo<'accounting-po', '/accounting/PO', Record<never, never>, Record<never, never>>,
    'accounting-rpt': RouteRecordInfo<'accounting-rpt', '/accounting/RPT', Record<never, never>, Record<never, never>>,
    'carrier-container-tracking': RouteRecordInfo<'carrier-container-tracking', '/carrier/container-tracking', Record<never, never>, Record<never, never>>,
    'carrier-flight-schedule': RouteRecordInfo<'carrier-flight-schedule', '/carrier/flight-schedule', Record<never, never>, Record<never, never>>,
    'carrier-vessel-sailing': RouteRecordInfo<'carrier-vessel-sailing', '/carrier/vessel-sailing', Record<never, never>, Record<never, never>>,
    'client': RouteRecordInfo<'client', '/client', Record<never, never>, Record<never, never>>,
    'client-id': RouteRecordInfo<'client-id', '/client/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'consolidation': RouteRecordInfo<'consolidation', '/consolidation', Record<never, never>, Record<never, never>>,
    'consolidation-id': RouteRecordInfo<'consolidation-id', '/consolidation/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'crm-activities': RouteRecordInfo<'crm-activities', '/crm/activities', Record<never, never>, Record<never, never>>,
    'crm-leads': RouteRecordInfo<'crm-leads', '/crm/leads', Record<never, never>, Record<never, never>>,
    'crm-opportunities': RouteRecordInfo<'crm-opportunities', '/crm/opportunities', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'library-charge-type-charge-transport-type': RouteRecordInfo<'library-charge-type-charge-transport-type', '/library/:chargeType-charge/:transportType', { chargeType: ParamValue<true>, transportType: ParamValue<true> }, { chargeType: ParamValue<false>, transportType: ParamValue<false> }>,
    'library-charge-type-charge-type': RouteRecordInfo<'library-charge-type-charge-type', '/library/:chargeType-charge/type', { chargeType: ParamValue<true> }, { chargeType: ParamValue<false> }>,
    'library-cargo-claim': RouteRecordInfo<'library-cargo-claim', '/library/cargo-claim', Record<never, never>, Record<never, never>>,
    'library-carrier-event-mapping': RouteRecordInfo<'library-carrier-event-mapping', '/library/carrier-event-mapping', Record<never, never>, Record<never, never>>,
    'library-data-retention': RouteRecordInfo<'library-data-retention', '/library/data-retention', Record<never, never>, Record<never, never>>,
    'library-duty-rate': RouteRecordInfo<'library-duty-rate', '/library/duty-rate', Record<never, never>, Record<never, never>>,
    'library-emission-factor': RouteRecordInfo<'library-emission-factor', '/library/emission-factor', Record<never, never>, Record<never, never>>,
    'library-free-time-agreement': RouteRecordInfo<'library-free-time-agreement', '/library/free-time-agreement', Record<never, never>, Record<never, never>>,
    'library-hs-code': RouteRecordInfo<'library-hs-code', '/library/hs-code', Record<never, never>, Record<never, never>>,
    'library-hs-restriction': RouteRecordInfo<'library-hs-restriction', '/library/hs-restriction', Record<never, never>, Record<never, never>>,
    'library-incoterm': RouteRecordInfo<'library-incoterm', '/library/incoterm', Record<never, never>, Record<never, never>>,
    'library-insurance-policy': RouteRecordInfo<'library-insurance-policy', '/library/insurance-policy', Record<never, never>, Record<never, never>>,
    'library-package-type-transport-type': RouteRecordInfo<'library-package-type-transport-type', '/library/package-type/:transportType', { transportType: ParamValue<true> }, { transportType: ParamValue<false> }>,
    'library-payment-method': RouteRecordInfo<'library-payment-method', '/library/payment-method', Record<never, never>, Record<never, never>>,
    'library-sanctions-list': RouteRecordInfo<'library-sanctions-list', '/library/sanctions-list', Record<never, never>, Record<never, never>>,
    'library-shipment-mode': RouteRecordInfo<'library-shipment-mode', '/library/shipment-mode', Record<never, never>, Record<never, never>>,
    'library-tax-exemption': RouteRecordInfo<'library-tax-exemption', '/library/tax-exemption', Record<never, never>, Record<never, never>>,
    'library-tax-group': RouteRecordInfo<'library-tax-group', '/library/tax-group', Record<never, never>, Record<never, never>>,
    'library-tax-registration': RouteRecordInfo<'library-tax-registration', '/library/tax-registration', Record<never, never>, Record<never, never>>,
    'library-tax-rule': RouteRecordInfo<'library-tax-rule', '/library/tax-rule', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'login-with-token-token-email': RouteRecordInfo<'login-with-token-token-email', '/login-with-token/:token/:email', { token: ParamValue<true>, email: ParamValue<true> }, { token: ParamValue<false>, email: ParamValue<false> }>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'portal-dashboard': RouteRecordInfo<'portal-dashboard', '/portal/dashboard', Record<never, never>, Record<never, never>>,
    'portal-documents': RouteRecordInfo<'portal-documents', '/portal/documents', Record<never, never>, Record<never, never>>,
    'portal-invoices': RouteRecordInfo<'portal-invoices', '/portal/invoices', Record<never, never>, Record<never, never>>,
    'portal-login': RouteRecordInfo<'portal-login', '/portal/login', Record<never, never>, Record<never, never>>,
    'portal-quote-request': RouteRecordInfo<'portal-quote-request', '/portal/quote-request', Record<never, never>, Record<never, never>>,
    'portal-shipments': RouteRecordInfo<'portal-shipments', '/portal/shipments', Record<never, never>, Record<never, never>>,
    'portal-shipments-id': RouteRecordInfo<'portal-shipments-id', '/portal/shipments/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'provider-provider-type': RouteRecordInfo<'provider-provider-type', '/provider/:providerType', { providerType: ParamValue<true> }, { providerType: ParamValue<false> }>,
    'provider-id-id': RouteRecordInfo<'provider-id-id', '/provider/id-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'quote-transport-type': RouteRecordInfo<'quote-transport-type', '/quote/:transportType', { transportType: ParamValue<true> }, { transportType: ParamValue<false> }>,
    'quote-preview-id': RouteRecordInfo<'quote-preview-id', '/quote/preview/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'quote-request': RouteRecordInfo<'quote-request', '/quote/request', Record<never, never>, Record<never, never>>,
    'quote-update-id': RouteRecordInfo<'quote-update-id', '/quote/update/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'rate-customs-transport-type': RouteRecordInfo<'rate-customs-transport-type', '/rate/customs/:transportType', { transportType: ParamValue<true> }, { transportType: ParamValue<false> }>,
    'rate-freight-transport-type': RouteRecordInfo<'rate-freight-transport-type', '/rate/freight/:transportType', { transportType: ParamValue<true> }, { transportType: ParamValue<false> }>,
    'rate-import': RouteRecordInfo<'rate-import', '/rate/import', Record<never, never>, Record<never, never>>,
    'rate-local-transport-type': RouteRecordInfo<'rate-local-transport-type', '/rate/local/:transportType', { transportType: ParamValue<true> }, { transportType: ParamValue<false> }>,
    'rate-markup': RouteRecordInfo<'rate-markup', '/rate/markup', Record<never, never>, Record<never, never>>,
    'rate-service-transport-type': RouteRecordInfo<'rate-service-transport-type', '/rate/service/:transportType', { transportType: ParamValue<true> }, { transportType: ParamValue<false> }>,
    'register-token': RouteRecordInfo<'register-token', '/register/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    'report': RouteRecordInfo<'report', '/report', Record<never, never>, Record<never, never>>,
    'report-audit-log': RouteRecordInfo<'report-audit-log', '/report/audit-log', Record<never, never>, Record<never, never>>,
    'report-carrier-performance': RouteRecordInfo<'report-carrier-performance', '/report/carrier-performance', Record<never, never>, Record<never, never>>,
    'report-charge': RouteRecordInfo<'report-charge', '/report/charge', Record<never, never>, Record<never, never>>,
    'report-co2-emissions': RouteRecordInfo<'report-co2-emissions', '/report/co2-emissions', Record<never, never>, Record<never, never>>,
    'report-compliance-dashboard': RouteRecordInfo<'report-compliance-dashboard', '/report/compliance-dashboard', Record<never, never>, Record<never, never>>,
    'report-customer-profitability': RouteRecordInfo<'report-customer-profitability', '/report/customer-profitability', Record<never, never>, Record<never, never>>,
    'report-dataset': RouteRecordInfo<'report-dataset', '/report/dataset', Record<never, never>, Record<never, never>>,
    'report-dd-dashboard': RouteRecordInfo<'report-dd-dashboard', '/report/dd-dashboard', Record<never, never>, Record<never, never>>,
    'report-department-pnl': RouteRecordInfo<'report-department-pnl', '/report/department-pnl', Record<never, never>, Record<never, never>>,
    'report-edi-log': RouteRecordInfo<'report-edi-log', '/report/edi-log', Record<never, never>, Record<never, never>>,
    'report-exception': RouteRecordInfo<'report-exception', '/report/exception', Record<never, never>, Record<never, never>>,
    'report-insurance-declaration': RouteRecordInfo<'report-insurance-declaration', '/report/insurance-declaration', Record<never, never>, Record<never, never>>,
    'report-kpi': RouteRecordInfo<'report-kpi', '/report/kpi', Record<never, never>, Record<never, never>>,
    'report-rate-benchmark': RouteRecordInfo<'report-rate-benchmark', '/report/rate-benchmark', Record<never, never>, Record<never, never>>,
    'report-sales-commission': RouteRecordInfo<'report-sales-commission', '/report/sales-commission', Record<never, never>, Record<never, never>>,
    'report-sales-target': RouteRecordInfo<'report-sales-target', '/report/sales-target', Record<never, never>, Record<never, never>>,
    'report-shipment': RouteRecordInfo<'report-shipment', '/report/shipment', Record<never, never>, Record<never, never>>,
    'report-staff': RouteRecordInfo<'report-staff', '/report/staff', Record<never, never>, Record<never, never>>,
    'report-top-lanes': RouteRecordInfo<'report-top-lanes', '/report/top-lanes', Record<never, never>, Record<never, never>>,
    'report-vat-report': RouteRecordInfo<'report-vat-report', '/report/vat-report', Record<never, never>, Record<never, never>>,
    'setting-branch': RouteRecordInfo<'setting-branch', '/setting/branch', Record<never, never>, Record<never, never>>,
    'setting-chart-of-accounts': RouteRecordInfo<'setting-chart-of-accounts', '/setting/chart-of-accounts', Record<never, never>, Record<never, never>>,
    'setting-company': RouteRecordInfo<'setting-company', '/setting/company', Record<never, never>, Record<never, never>>,
    'setting-department': RouteRecordInfo<'setting-department', '/setting/department', Record<never, never>, Record<never, never>>,
    'setting-global-setting': RouteRecordInfo<'setting-global-setting', '/setting/global-setting', Record<never, never>, Record<never, never>>,
    'setting-groups': RouteRecordInfo<'setting-groups', '/setting/groups', Record<never, never>, Record<never, never>>,
    'setting-integration-connectors': RouteRecordInfo<'setting-integration-connectors', '/setting/integration-connectors', Record<never, never>, Record<never, never>>,
    'setting-pages': RouteRecordInfo<'setting-pages', '/setting/pages', Record<never, never>, Record<never, never>>,
    'setting-users': RouteRecordInfo<'setting-users', '/setting/users', Record<never, never>, Record<never, never>>,
    'shipment-id-tab1?tab2?': RouteRecordInfo<'shipment-id-tab1?tab2?', '/shipment/:id/:tab1?-:tab2?', { id: ParamValue<true>, tab1?: ParamValueZeroOrOne<true>, tab2?: ParamValueZeroOrOne<true> }, { id: ParamValue<false>, tab1?: ParamValueZeroOrOne<false>, tab2?: ParamValueZeroOrOne<false> }>,
    'shipment-transport-type': RouteRecordInfo<'shipment-transport-type', '/shipment/:transportType', { transportType: ParamValue<true> }, { transportType: ParamValue<false> }>,
    'shipment-manifest': RouteRecordInfo<'shipment-manifest', '/shipment/manifest', Record<never, never>, Record<never, never>>,
    'test': RouteRecordInfo<'test', '/test', Record<never, never>, Record<never, never>>,
    'test2': RouteRecordInfo<'test2', '/test2', Record<never, never>, Record<never, never>>,
    'test3': RouteRecordInfo<'test3', '/test3', Record<never, never>, Record<never, never>>,
    'user-settings': RouteRecordInfo<'user-settings', '/user-settings', Record<never, never>, Record<never, never>>,
    'warehouse-facility': RouteRecordInfo<'warehouse-facility', '/warehouse/facility', Record<never, never>, Record<never, never>>,
    'warehouse-inventory': RouteRecordInfo<'warehouse-inventory', '/warehouse/inventory', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
