export const Feature = Object.freeze({
  // Core Pro
  Branches:                 1,
  Departments:              2,
  PagesCms:                 3,
  Components:               4,
  ConfigurableShipmentId:   5,
  // Quote Pro
  FreeTimeAgreements:       6,
  PriceMarkupRules:         7,
  RateImport:               8,
  // Operations Pro
  Consolidations:           9,
  ArrivalNotices:           10,
  ShipmentDocuments:        11,
  ShipmentNotes:            12,
  ShipmentParties:          13,
  ShipmentTasks:            14,
  DocumentGeneration:       15,
  RoadFreight:              16,
  RailFreight:              17,
  Multimodal:               18,
  CourierExpress:           19,
  WarehouseCfs:             20,
  // Finance Pro
  GeneralLedger:            21,
  ChartOfAccounts:          22,
  CurrencyManagement:       23,
  ArAgeing:                 24,
  PLReports:                25,
  CreditControl:            26,
  DdCalculator:             27,
  // Tax Pro
  HsCodes:                  28,
  DutyRates:                29,
  HsRestrictions:           30,
  HsVersionMapping:         31,
  VatReporting:             32,
  PartnerTaxRegistration:   33,
  CustomerTaxExemption:     34,
  // Carrier Pro
  CarrierProviders:         35,
  CarrierProfiles:          36,
  ContainerTracking:        37,
  CarrierEventMappings:     38,
  CarrierPerformanceScore:  39,
  DdTracking:               40,
  VesselRollAlerts:         41,
  VesselSailingSchedule:    42,
  FlightSchedule:           43,
  CargoClaims:              44,
  CargoInsurance:           45,
  // CRM Pro
  CrmContacts:              47,
  CrmPartners:              48,
  CrmAgentProfiles:         49,
  SalesCrm:                 50,
  // Notification Pro
  EmailNotifications:       51,
  InAppNotifications:       52,
  NotificationRules:        53,
  NotificationTemplates:    54,
  NotificationQueue:        55,
  // Reporting Pro
  KpiDashboards:            56,
  RevenueAnalytics:         57,
  CustomDatasets:           58,
  // Business
  RateBenchmarking:         59,
  Co2Emissions:             60,
  AuditLogCompliance:       61,
  CustomerPortalAuth:       62,
  CustomerPortalShipments:  63,
  CustomerPortalDocuments:  64,
  CustomerPortalInvoices:   65,
  CustomerPortalQuoteRequests: 66,
  LetterOfCredit:           67,
  CustomsFiling:            68,
  EdiIntegration:           69,
})
